on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  campsite_contributions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update campsite_contributions.json
        run: |
          sudo apt-get install libxml2-utils

          rm ./data/campsite_contributions.json
          ./.github/workflows/fetch_campsite_contributions.sh > ./data/campsite_contributions.json

          if git diff --quiet; then
            echo "No new contributions"
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update Campsite contributions"
            git push
          fi
